In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import sklearn.linear_model as lm
import sklearn.metrics as mt
from mpl_toolkits.mplot3d import Axes3D
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestRegressor

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
data = pd.read_csv('/content/drive/My Drive/BRCA.csv')

In [ ]:
data.head()

Patient_ID   Age  Gender  Protein1  Protein2  Protein3  Protein4  \
0  TCGA-D8-A1XD  36.0  FEMALE  0.080353   0.42638   0.54715  0.273680   
1  TCGA-EW-A1OX  43.0  FEMALE -0.420320   0.57807   0.61447 -0.031505   
2  TCGA-A8-A079  69.0  FEMALE  0.213980   1.31140  -0.32747 -0.234260   
3  TCGA-D8-A1XR  56.0  FEMALE  0.345090  -0.21147  -0.19304  0.124270   
4  TCGA-BH-A0BF  56.0  FEMALE  0.221550   1.90680   0.52045 -0.311990   

  Tumour_Stage                      Histology ER status PR status HER2 status  \
0          III  Infiltrating Ductal Carcinoma  Positive  Positive    Negative   
1           II             Mucinous Carcinoma  Positive  Positive    Negative   
2          III  Infiltrating Ductal Carcinoma  Positive  Positive    Negative   
3           II  Infiltrating Ductal Carcinoma  Positive  Positive    Negative   
4           II  Infiltrating Ductal Carcinoma  Positive  Positive    Negative   

                  Surgery_type Date_of_Surgery Date_of_Last_Visit  \
0  Modified Radical Mastectomy       15-Jan-17          19-Jun-17   
1                   Lumpectomy       26-Apr-17          09-Nov-18   
2                        Other       08-Sep-17          09-Jun-18   
3  Modified Radical Mastectomy       25-Jan-17          12-Jul-17   
4                        Other       06-May-17          27-Jun-19   

  Patient_Status  
0          Alive  
1           Dead  
2          Alive  
3          Alive  
4           Dead

In [ ]:
#data['Tumour_Stage'] = data['Tumour_Stage'].replace(['III', 'II', 'I'], ['3', '2', '1'])

In [ ]:
Tumour= pd.get_dummies(data['Tumour_Stage'])

In [ ]:
print(Tumour)

     I  II  III
0    0   0    1
1    0   1    0
2    0   0    1
3    0   1    0
4    0   1    0
..  ..  ..  ...
336  0   0    0
337  0   0    0
338  0   0    0
339  0   0    0
340  0   0    0

[341 rows x 3 columns]


In [ ]:
data= pd.concat((Tumour, data), axis=1)

In [ ]:
data = data.drop(["Tumour_Stage"], axis=1)

In [ ]:
#data['Histology'] = data['Histology'].replace(['Infiltrating Ductal Carcinoma', 'Mucinous Carcinoma', 'Infiltrating Lobular Carcinoma'], ['0', '1', '2'])

In [ ]:
New_Histology=pd.get_dummies(data['Histology'])

In [ ]:
data= pd.concat((New_Histology, data), axis=1)

In [ ]:
data = data.drop(["Histology"], axis=1)

In [ ]:
Sur_Type= pd.get_dummies(data['Surgery_type'])

In [ ]:
data= pd.concat((Sur_Type, data), axis=1)

In [ ]:
data = data.drop(["Surgery_type"], axis=1)

In [ ]:
#data['Surgery_type'] = data['Surgery_type'].replace(['Modified Radical Mastectomy', 'Lumpectomy', 'Simple Mastectomy','Other'], ['0', '1', '2','3'])

In [ ]:
Gender_New=pd.get_dummies(data["Gender"])

In [ ]:
data= pd.concat((Gender_New, data), axis=1)

In [ ]:
data = data.drop(["Gender"], axis=1)

In [ ]:
df=pd.get_dummies(data["Patient_Status"])

In [ ]:
print(df)

     Alive  Dead
0        1     0
1        0     1
2        1     0
3        1     0
4        0     1
..     ...   ...
336      0     0
337      0     0
338      0     0
339      0     0
340      0     0

[341 rows x 2 columns]


In [ ]:
data= pd.concat((df, data), axis=1)

In [ ]:
data = data.drop(["Patient_Status"], axis=1)

In [ ]:
data = data.drop(['Alive'], axis = 1)

In [ ]:
#data['Patient_Status'] = data['Patient_Status'].replace(['Alive', 'Dead'], ['0', '1',])

In [ ]:
#data['Gender'] = data['Gender'].replace(['MALE', 'FEMALE'], ['0', '1',])

In [ ]:
data=data.dropna()

In [ ]:
data = data.iloc[: , :-1]

In [ ]:
data.head()

Dead  FEMALE  MALE  Lumpectomy  Modified Radical Mastectomy  Other  \
0     0       1     0           0                            1      0   
1     1       1     0           1                            0      0   
2     0       1     0           0                            0      1   
3     0       1     0           0                            1      0   
4     1       1     0           0                            0      1   

   Simple Mastectomy  Infiltrating Ductal Carcinoma  \
0                  0                              1   
1                  0                              0   
2                  0                              1   
3                  0                              1   
4                  0                              1   

   Infiltrating Lobular Carcinoma  Mucinous Carcinoma  ...    Patient_ID  \
0                               0                   0  ...  TCGA-D8-A1XD   
1                               0                   1  ...  TCGA-EW-A1OX   
2                               0                   0  ...  TCGA-A8-A079   
3                               0                   0  ...  TCGA-D8-A1XR   
4                               0                   0  ...  TCGA-BH-A0BF   

    Age  Protein1 Protein2  Protein3  Protein4  ER status  PR status  \
0  36.0  0.080353  0.42638   0.54715  0.273680   Positive   Positive   
1  43.0 -0.420320  0.57807   0.61447 -0.031505   Positive   Positive   
2  69.0  0.213980  1.31140  -0.32747 -0.234260   Positive   Positive   
3  56.0  0.345090 -0.21147  -0.19304  0.124270   Positive   Positive   
4  56.0  0.221550  1.90680   0.52045 -0.311990   Positive   Positive   

   HER2 status Date_of_Surgery  
0     Negative       15-Jan-17  
1     Negative       26-Apr-17  
2     Negative       08-Sep-17  
3     Negative       25-Jan-17  
4     Negative       06-May-17  

[5 rows x 23 columns]

In [ ]:
data_clean = data[['Age','FEMALE','MALE','Protein1','Protein2','Protein3','Protein4','I','II','III','Infiltrating Ductal Carcinoma','Infiltrating Lobular Carcinoma','Mucinous Carcinoma','Lumpectomy','Modified Radical Mastectomy','Other','Dead']]

In [ ]:
data_clean.head()

Age  FEMALE  MALE  Protein1  Protein2  Protein3  Protein4  I  II  III  \
0  36.0       1     0  0.080353   0.42638   0.54715  0.273680  0   0    1   
1  43.0       1     0 -0.420320   0.57807   0.61447 -0.031505  0   1    0   
2  69.0       1     0  0.213980   1.31140  -0.32747 -0.234260  0   0    1   
3  56.0       1     0  0.345090  -0.21147  -0.19304  0.124270  0   1    0   
4  56.0       1     0  0.221550   1.90680   0.52045 -0.311990  0   1    0   

   Infiltrating Ductal Carcinoma  Infiltrating Lobular Carcinoma  \
0                              1                               0   
1                              0                               0   
2                              1                               0   
3                              1                               0   
4                              1                               0   

   Mucinous Carcinoma  Lumpectomy  Modified Radical Mastectomy  Other  Dead  
0                   0           0                            1      0     0  
1                   1           1                            0      0     1  
2                   0           0                            0      1     0  
3                   0           0                            1      0     0  
4                   0           0                            0      1     1

In [ ]:
reg = lm.LogisticRegression(max_iter=10000)
reg.fit(data_clean[['Age','FEMALE','MALE','Protein1','Protein2','Protein3','Protein4','I','II','III','Infiltrating Ductal Carcinoma','Infiltrating Lobular Carcinoma','Mucinous Carcinoma','Lumpectomy','Modified Radical Mastectomy','Other',]], data_clean['Dead'])
reg.intercept_, reg.coef_

(array([-1.3735587]),
 array([[-0.00247204, -0.14622067,  0.13929774, -0.17925016,  0.29051672,
          0.22117526,  0.34803433, -0.26758999,  0.05185475,  0.20881231,
         -0.05134433, -0.30450111,  0.34892252, -0.40108404, -0.07310225,
          0.32761909]]))

In [ ]:
train, test = train_test_split(data_clean, test_size = 0.2)

In [ ]:
reg.fit(train[['Age','FEMALE','MALE','Protein1','Protein2','Protein3','Protein4','I','II','III','Infiltrating Ductal Carcinoma','Infiltrating Lobular Carcinoma','Mucinous Carcinoma','Lumpectomy','Modified Radical Mastectomy','Other']], train['Dead'])
reg.intercept_, reg.coef_

(array([-1.73700396]),
 array([[-2.05264142e-04, -1.35185756e-01,  1.22868360e-01,
         -4.78307452e-02,  4.26428759e-01,  3.50374545e-01,
          3.46269321e-01, -1.98959506e-01, -2.13668719e-02,
          2.08008983e-01,  4.98729511e-02, -2.80196717e-01,
          2.18006370e-01, -4.84555135e-01,  9.74773598e-02,
          1.00522022e-01]]))

In [ ]:
death_predict = reg.predict(test[['Age','FEMALE','MALE','Protein1','Protein2','Protein3','Protein4','I','II','III','Infiltrating Ductal Carcinoma','Infiltrating Lobular Carcinoma','Mucinous Carcinoma','Lumpectomy','Modified Radical Mastectomy','Other']])

In [ ]:
print(death_predict)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
print(mt.mean_squared_error(test['Dead'],death_predict))

0.203125


In [ ]:

model = RandomForestRegressor()

In [ ]:
model.fit(train[['Age','FEMALE','MALE','Protein1','Protein2','Protein3','Protein4','I','II','III','Infiltrating Ductal Carcinoma','Infiltrating Lobular Carcinoma','Mucinous Carcinoma','Lumpectomy','Modified Radical Mastectomy','Other']], train['Dead'])

RandomForestRegressor()

In [ ]:
death_predict_2 = model.predict(test[['Age','FEMALE','MALE','Protein1','Protein2','Protein3','Protein4','I','II','III','Infiltrating Ductal Carcinoma','Infiltrating Lobular Carcinoma','Mucinous Carcinoma','Lumpectomy','Modified Radical Mastectomy','Other']])

In [ ]:
print(death_predict_2)

[0.17 0.23 0.09 0.12 0.16 0.44 0.21 0.21 0.57 0.33 0.35 0.23 0.14 0.33
 0.05 0.17 0.11 0.23 0.43 0.37 0.06 0.11 0.42 0.26 0.11 0.26 0.19 0.24
 0.09 0.21 0.2  0.18 0.08 0.14 0.24 0.16 0.45 0.12 0.11 0.09 0.45 0.16
 0.13 0.08 0.23 0.08 0.19 0.13 0.23 0.28 0.05 0.34 0.05 0.45 0.33 0.17
 0.18 0.16 0.07 0.14 0.08 0.34 0.42 0.18]


In [ ]:
print(mt.mean_squared_error(test['Dead'], death_predict_2))

0.1693875
